/*
 * Copyright (c) Mirth Corporation. All rights reserved.
 *
 * http://www.mirthcorp.com
 *
 * The software in this package is published under the terms of the MPL license a copy of which has
 * been included with this distribution in the LICENSE.txt file.
 */

package com.mirth.connect.plugins.xsltstep;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.util.LinkedList;

import org.apache.commons.io.FileUtils;
import org.apache.commons.text.StringEscapeUtils;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import com.mirth.connect.donkey.model.message.ConnectorMessage;
import com.mirth.connect.model.IteratorProperties;
import com.mirth.connect.model.Step;
import com.mirth.connect.util.JavaScriptTestUtil;

/**
 * Regression tests for CVE-2026-78224: the script generated by the XSLT step created a
 * TransformerFactory with default settings, so a DOCTYPE in the (attacker-controlled) source XML
 * could read server-local files through external entities or stall the channel on a slow entity.
 */
public class XsltStepTest {

    private static final String CANARY = "XSLT_XXE_CANARY_7f3a9c";
    private static final String RESULT_VARIABLE = "xsltResult";

    // @formatter:off
    private static final String IDENTITY_TEMPLATE =
        "<xsl:stylesheet version=\"1.0\" xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\">" +
        "    <xsl:output method=\"xml\" omit-xml-declaration=\"yes\"/>" +
        "    <xsl:template match=\"/\">" +
        "        <xsl:copy-of select=\".\"/>" +
        "    </xsl:template>" +
        "</xsl:stylesheet>";
    // @formatter:on

    @Rule
    public TemporaryFolder tempFolder = new TemporaryFolder();

    @BeforeClass
    public static void setup() throws Exception {
        JavaScriptTestUtil.setup();
    }

    @Test
    public void testGeneratedScriptHardensTransformerFactory() throws Exception {
        XsltStep step = newStep("'<d/>'", IDENTITY_TEMPLATE);

        assertHardened(step.getScript(true));
        assertHardened(step.getIterationScript(true, new LinkedList<IteratorProperties<Step>>()));
    }

    @Test
    public void testGeneratedScriptHardensCustomTransformerFactory() throws Exception {
        XsltStep step = newStep("'<d/>'", IDENTITY_TEMPLATE);
        step.setUseCustomFactory(true);
        step.setCustomFactory("com.example.CustomTransformerFactory");

        String script = step.getScript(true);
        assertTrue(script.contains("TransformerFactory.newInstance(\"com.example.CustomTransformerFactory\", null)"));
        assertHardened(script);
    }

    @Test
    public void testBenignXmlStillTransforms() throws Exception {
        XsltStep step = newStep("'<d><v>1</v></d>'", IDENTITY_TEMPLATE);

        String result = transform(step);

        assertEquals("<d><v>1</v></d>", result);
    }

    @Test
    public void testExternalGeneralEntityIsNotResolved() throws Exception {
        File secret = writeCanaryFile("secret.txt");
        String sourceXml = "<?xml version=\"1.0\"?><!DOCTYPE d [<!ENTITY x SYSTEM \"" + secret.toURI() + "\">]><d>&x;</d>";
        XsltStep step = newStep(jsLiteral(sourceXml), IDENTITY_TEMPLATE);

        assertCanaryNotLeaked(step);
    }

    @Test
    public void testExternalDtdIsNotLoaded() throws Exception {
        File secret = writeCanaryFile("secret.txt");
        File dtd = new File(tempFolder.getRoot(), "leak.dtd");
        FileUtils.writeStringToFile(dtd, "<!ENTITY x SYSTEM \"" + secret.toURI() + "\">", StandardCharsets.UTF_8);
        String sourceXml = "<?xml version=\"1.0\"?><!DOCTYPE d SYSTEM \"" + dtd.toURI() + "\"><d>&x;</d>";
        XsltStep step = newStep(jsLiteral(sourceXml), IDENTITY_TEMPLATE);

        assertCanaryNotLeaked(step);
    }

    @Test
    public void testExternalEntityIsNotResolvedWithCustomFactory() throws Exception {
        File secret = writeCanaryFile("secret.txt");
        String sourceXml = "<?xml version=\"1.0\"?><!DOCTYPE d [<!ENTITY x SYSTEM \"" + secret.toURI() + "\">]><d>&x;</d>";
        XsltStep step = newStep(jsLiteral(sourceXml), IDENTITY_TEMPLATE);
        step.setUseCustomFactory(true);
        step.setCustomFactory("com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl");

        assertCanaryNotLeaked(step);
    }

    private void assertCanaryNotLeaked(XsltStep step) throws Exception {
        String result = null;
        Exception failure = null;

        try {
            result = transform(step);
        } catch (Exception e) {
            failure = e;
        }

        if (result != null) {
            assertFalse("external entity was resolved: " + result, result.contains(CANARY));
        }
        if (failure != null) {
            assertFalse("external entity was resolved: " + failure.getMessage(), String.valueOf(failure.getMessage()).contains(CANARY));
        }
    }

    private static void assertHardened(String script) {
        assertTrue(script, script.contains("tFactory.setAttribute(Packages.javax.xml.XMLConstants.ACCESS_EXTERNAL_DTD, '')"));
        assertTrue(script, script.contains("tFactory.setAttribute(Packages.javax.xml.XMLConstants.ACCESS_EXTERNAL_STYLESHEET, '')"));
        // The factory must be hardened before it is used
        assertTrue(script.indexOf("ACCESS_EXTERNAL_DTD") < script.indexOf("tFactory.newTransformer("));
    }

    private static XsltStep newStep(String sourceXml, String template) {
        XsltStep step = new XsltStep();
        step.setSourceXml(sourceXml);
        step.setResultVariable(RESULT_VARIABLE);
        step.setTemplate(template);
        return step;
    }

    private static String transform(XsltStep step) throws Exception {
        ConnectorMessage connectorMessage = new ConnectorMessage();
        JavaScriptTestUtil.testTransformerStep(step, connectorMessage);
        Object result = connectorMessage.getChannelMap().get(RESULT_VARIABLE);
        assertNotNull(result);
        return result.toString();
    }

    private File writeCanaryFile(String name) throws Exception {
        File file = new File(tempFolder.getRoot(), name);
        FileUtils.writeStringToFile(file, CANARY, StandardCharsets.UTF_8);
        return file;
    }

    private static String jsLiteral(String value) {
        return "'" + StringEscapeUtils.escapeEcmaScript(value) + "'";
    }
}
