# Donkey Oracle Test Configuration

database = oracle
database.url = jdbc:oracle:thin:@//localhost:1521/FREEPDB1
database.driver = oracle.jdbc.OracleDriver
database.jdbc4 = true
database.username = mirthdb
database.password = mirthdb
database.max-connections = 10
