# Donkey PostgreSQL Test Configuration

database = postgres
database.url = jdbc:postgresql://localhost:5432/mirthdb
database.driver = org.postgresql.Driver
database.jdbc4 = true
database.username = mirthdb
database.password = mirthdb
database.max-connections = 10
