-- PostgreSQL

CREATE TABLE IF NOT EXISTS LOOKUP_GROUP_EXTRA (
    GROUP_ID INTEGER NOT NULL,
    VALUE_TYPE      VARCHAR(10) NOT NULL DEFAULT 'TEXT',  -- TEXT | JSON
    JSON_INDEX_MODE VARCHAR(10),
    INDEXED_JSON_FIELDS  JSONB,
    PRIMARY KEY (GROUP_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES LOOKUP_GROUP(ID) ON DELETE CASCADE
);