-- SqlServer

-- Create LOOKUP_GROUP_EXTRA table
CREATE TABLE LOOKUP_GROUP_EXTRA (
    GROUP_ID INT NOT NULL PRIMARY KEY,
    JSON_INDEX_MODE NVARCHAR(10),
    INDEXED_JSON_FIELDS  NVARCHAR(MAX),
    FOREIGN KEY (GROUP_ID) REFERENCES LOOKUP_GROUP(ID) ON DELETE CASCADE
);