-- Oracle

CREATE TABLE LOOKUP_GROUP_EXTRA (
    GROUP_ID NUMBER PRIMARY KEY,
    JSON_INDEX_MODE VARCHAR2(10),
    INDEXED_JSON_FIELDS CLOB,
    CONSTRAINT CHK_LOOKUP_GROUP_EXTRA_JSON_FIELDS
        CHECK (INDEXED_JSON_FIELDS IS JSON),
    CONSTRAINT FK_LOOKUP_GROUP_EXTRA_GROUP FOREIGN KEY (GROUP_ID)
        REFERENCES LOOKUP_GROUP(ID) ON DELETE CASCADE
);